all :
	make -C assembly/ 
	make -C tp1/

fast:
	make -C assembly/ fast
	make -C tp1/ fast

drunk:
	make -C assembly/
	make -C tp1/ drunk

fibonacci:
	make -C assembly/ fibonacci
	make -C tp1/ fibonacci

clean :
	dune clean 

.PHONY: all clean